In [3]:
"""
Purchase 10000 of SP500 every month in a specific day
Compare the assed between the specific days
"""

import __init__

from backtest.accumulationStrategy import run_day_on_month

codename = "^GSPC" #SP500
startstr = "2019-01-01T00:00:00"
endstr = "2024-01-01T00:00:00"
orderstopstr = endstr

for day in range(1,28):
    trade_name = "acc_sp500_day%02d" % (day)
    run_day_on_month(trade_name, codename, "D", startstr, endstr, orderstopstr, day=day)
print("finished")

finished

In [4]:
import __init__

from db.mydf import MyDf
db = MyDf()
sql = """select trade_name, sum(units) * (select C FROM ohlcv_GSPC_D order by EP desc limit 1) as asset 
from trade_history where trade_name like 'acc_sp500_day%%' group by 1"""
db.read_sql(sql)

         trade_name          asset
0   acc_sp500_day01  823586.382466
1   acc_sp500_day02  822301.159269
2   acc_sp500_day03  824340.614815
3   acc_sp500_day04  819365.581614
4   acc_sp500_day05  819028.758195
5   acc_sp500_day06  818952.914541
6   acc_sp500_day07  820028.244255
7   acc_sp500_day08  818450.295487
8   acc_sp500_day09  818567.400637
9   acc_sp500_day10  816667.662883
10  acc_sp500_day11  819209.687743
11  acc_sp500_day12  820713.521906
12  acc_sp500_day13  817672.703216
13  acc_sp500_day14  819402.397323
14  acc_sp500_day15  817524.402948
15  acc_sp500_day16  816832.808349
16  acc_sp500_day17  815984.756161
17  acc_sp500_day18  818320.117070
18  acc_sp500_day19  818751.659196
19  acc_sp500_day20  819736.293202
20  acc_sp500_day21  819828.452681
21  acc_sp500_day22  819939.809337
22  acc_sp500_day23  820025.679105
23  acc_sp500_day24  817753.922317
24  acc_sp500_day25  817290.725573
25  acc_sp500_day26  816704.075938
26  acc_sp500_day27  804252.369805