In [1]:
from datetime import datetime

import __init__
from analyze.zigzagStrategy.predictor import ZzPredictor
import lib

trade_name = 'zzstrat_top3000vol'
start = lib.dt2epoch(datetime(2018, 1, 1))
end = lib.dt2epoch(datetime(2023, 1, 1))

z = ZzPredictor(trade_name, start, end)
z.train(high_threshold=0.6, low_threshold=0.4)
z.printResult()

{'high_threshold': 0.6, 'accuracy_high': 0.5454545454545454, 'precision_high': 0.5454545454545454, 'recall_high': 0.5454545454545454, 'f1_high': 0.5454545454545454, 'count_above_high_threshold': 33, 'low_threshold': 0.4, 'accuracy_low': 0.45454545454545453, 'precision_low': 0.45454545454545453, 'recall_low': 0.45454545454545453, 'f1_low': 0.45454545454545453, 'count_below_low_threshold': 33}

In [2]:
import pandas as pd
pd.options.display.max_rows = 200

from db.pgdf import PgDf
pg = PgDf()

start = lib.dt2epoch(datetime(2023, 1, 1))
end = lib.dt2epoch(datetime(2024, 1, 1))

df = z.predict_trades(start, end)


print("total: %d" % len(df))
print("win: %d" % len(df[df['result'] == 1]))

total: 467
win: 239

In [3]:
df = df[df.predicted != 0]

ok = len(df[df.predicted == df.result])
total = len(df)
print("total predicted: %d" % len(df))
print("accurracy: %f" % (float(ok)/float(total)))

total predicted: 113
accurracy: 0.513274

In [4]:
df

    codename         dt  predicted  proba  result
0     1605.T 2023-01-04         -1   0.35       1
2     7453.T 2023-01-05          1   0.63       1
4     8058.T 2023-01-04         -1   0.38      -1
6     9020.T 2023-01-05          1   0.73      -1
7     3382.T 2023-01-11         -1   0.38      -1
8     9202.T 2023-01-04          1   0.65       1
16    9984.T 2023-01-10          1   0.61       1
17    3563.T 2023-01-11          1   0.61      -1
20    6954.T 2023-01-12          1   0.61      -1
21    9503.T 2023-01-19          1   0.67       1
25    9433.T 2023-01-23          1   0.68       1
30    8725.T 2023-02-02          1   0.71       1
38    6098.T 2023-02-02         -1   0.38       1
41    2413.T 2023-02-09          1   0.61      -1
48    1605.T 2023-02-13         -1   0.31       1
54    3099.T 2023-02-20          1   0.63       1
56    8750.T 2023-02-20          1   0.63      -1
71    9503.T 2023-02-28         -1   0.37       1
72    3099.T 2023-03-02          1   0.63      -1
77    9021.T 2023-03-07         -1   0.34      -1
78    9434.T 2023-03-07         -1   0.37      -1
83    5727.T 2023-03-08         -1   0.35       1
85    9503.T 2023-03-08         -1   0.38       1
86    9502.T 2023-03-08         -1   0.31       1
95    8267.T 2023-03-15          1   0.65       1
110   3088.T 2023-03-29          1   0.66      -1
114   1925.T 2023-04-03          1   0.62      -1
117   9502.T 2023-04-03         -1   0.38       1
122   9005.T 2023-04-11         -1   0.32      -1
128   5727.T 2023-04-13          1   0.68      -1
129   8035.T 2023-04-18          1   0.65       1
145   8795.T 2023-04-27          1   0.61       1
146   7731.T 2023-04-27         -1   0.39      -1
150   8031.T 2023-05-09          1   0.61       1
153   8795.T 2023-05-09          1   0.66      -1
157   6857.T 2023-05-11         -1   0.35      -1
160   6963.T 2023-05-11          1   0.72      -1
166   6981.T 2023-05-15          1   0.62      -1
168   7203.T 2023-05-17         -1   0.35       1
175   2914.T 2023-05-16          1   0.68       1
179   6954.T 2023-05-22         -1   0.38       1
181   9531.T 2023-05-24         -1   0.37      -1
185   4543.T 2023-06-01          1   0.68      -1
190   6963.T 2023-05-29         -1   0.38      -1
191   4452.T 2023-05-30         -1   0.33       1
197   6963.T 2023-06-07          1   0.77       1
199   6301.T 2023-06-06          1   0.69       1
206   3099.T 2023-06-05          1   0.65       1
217   8766.T 2023-06-14          1   0.61       1
219   4503.T 2023-06-22          1   0.64      -1
227   8309.T 2023-07-03          1   0.71      -1
229   5406.T 2023-07-03         -1   0.28      -1
231   6619.T 2023-07-04          1   0.76       1
234   7735.T 2023-07-04         -1   0.34       1
235   9434.T 2023-07-05          1   0.70       1
237   3436.T 2023-06-28          1   0.66       1
238   9434.T 2023-06-29          1   0.62      -1
240   6971.T 2023-07-06          1   0.62       1
243   8267.T 2023-07-06          1   0.68       1
249   1570.T 2023-07-06          1   0.65      -1
251   8316.T 2023-07-10          1   0.70       1
252   6902.T 2023-07-11         -1   0.36       1
254   5411.T 2023-07-19         -1   0.38      -1
262   4901.T 2023-07-24          1   0.74      -1
266   9104.T 2023-07-19          1   0.61       1
272   8411.T 2023-07-27          1   0.80      -1
279   9984.T 2023-07-26          1   0.62       1
281   2503.T 2023-08-03          1   0.68       1
283   3436.T 2023-08-03         -1   0.26      -1
297   9021.T 2023-08-09         -1   0.39       1
298   8591.T 2023-08-17         -1   0.39       1
314   4503.T 2023-08-21         -1   0.37       1
315   5406.T 2023-08-28          1   0.65      -1
325   8750.T 2023-09-05          1   0.62      -1
334   7453.T 2023-09-14          1   0.64       1
338   5108.T 2023-09-13         -1   0.31      -1
341   9202.T 2023-09-20         -1   0.39       1
344   4543.T 2023-09-21          1   0.62      -1
345   4661.T 2023-09-21         -1   0.37      -1
348   4502.T 2023-10-02         -1   0.36      -1
353   8053.T 2023-10-04         -1   0.29      -1
362   9021.T 2023-10-03         -1   0.35      -1
365   4385.T 2023-10-11         -1   0.34       1
373   4385.T 2023-10-23          1   0.69       1
377   6963.T 2023-10-19         -1   0.39      -1
378   7453.T 2023-10-16         -1   0.35      -1
379   8316.T 2023-10-23          1   0.61       1
382   6301.T 2023-10-23          1   0.67      -1
384   6503.T 2023-10-23         -1   0.35      -1
387   6902.T 2023-10-23         -1   0.30       1
388   8766.T 2023-10-23          1   0.69       1
392   8035.T 2023-10-26         -1   0.39       1
403   4063.T 2023-11-01          1   0.62      -1
404   8306.T 2023-11-08          1   0.64       1
405   8331.T 2023-11-08          1   0.63      -1
406   8411.T 2023-11-09          1   0.69      -1
407   8316.T 2023-11-08          1   0.71      -1
416   8309.T 2023-11-08          1   0.63      -1
417   9434.T 2023-11-09         -1   0.31       1
418   7731.T 2023-11-14         -1   0.39      -1
421   6702.T 2023-11-16         -1   0.35      -1
423   3099.T 2023-11-13         -1   0.37       1
424   7751.T 2023-11-13         -1   0.28       1
425   1928.T 2023-11-14          1   0.70       1
432   9434.T 2023-11-27         -1   0.39      -1
434   7751.T 2023-11-29         -1   0.21       1
442   7202.T 2023-11-30          1   0.62       1
451   2502.T 2023-12-13          1   0.71      -1
454   3659.T 2023-12-12         -1   0.32      -1
455   8411.T 2023-12-14          1   0.61      -1
456   6254.T 2023-12-14         -1   0.34      -1
458   8001.T 2023-12-18         -1   0.37       1
462   2503.T 2023-12-18          1   0.62       1