In [ ]:
import __init__

import pandas as pd
pd.set_option("display.max_rows", None, "display.max_columns", None)

from db.pgdf import PgDf
from db.postgresql import PostgreSqlDB

d = PostgreSqlDB()
pg = PgDf()

df = pg.read_sql("""WITH t AS (
SELECT 
t.profit,
CASE WHEN t.result = 'lose' THEN -1
    WHEN t.result = 'win' THEN 1
    ELSE 0
END AS result,
CASE WHEN (mado > 0) THEN 1 ELSE 0 END AS mado,
CASE WHEN (ABS(trend_rate) > 0.75) THEN 1 ELSE 0 END AS trend,
CASE WHEN len_std > 1.5 THEN 1 ELSE 0 END AS long_candle,
prefer_recent_peaks,
CASE WHEN (reversed_cnt > 1) THEN 1 ELSE 0 END AS reversed
FROM zz_strtg_params as z
JOIN trades as t ON t.order_id = z.order_id
WHERE t.trade_name = 'zzstrat_top100vol'
AND abs(t.profit) > 0
AND t.open_price > 1000
AND ABS(t.takeprofit_price - t.open_price)/ABS(t.stoploss_price - t.open_price) as ts_rate
), g AS (
SELECT COUNT(*) as cnt, result,mado,trend,long_candle,prefer_recent_peaks,reversed, (SUM(t.profit)/20000) as profit
FROM t
WHERE ts_rate > 0.8
GROUP BY result, mado,trend,long_candle,prefer_recent_peaks,reversed
)
SELECT * FROM g ORDER BY 3,4,5,6,7,2
;""")

In [29]:
df

,cnt,result,mado,trend,long_candle,prefer_recent_peaks,reversed,profit
0,34,-1,0,0,0,0,0,-46.876553
1,46,1,0,0,0,0,0,46.000000
2,20,-1,0,0,0,0,1,-24.451578
3,20,1,0,0,0,0,1,20.000000
4,91,-1,0,0,0,1,0,-141.483287
5,180,1,0,0,0,1,0,180.000000
6,136,-1,0,0,0,1,1,-205.650352
7,192,1,0,0,0,1,1,192.000000
8,2,-1,0,0,1,0,0,-2.726025
9,10,1,0,0,1,0,0,10.000000
10,8,-1,0,0,1,0,1,-7.341206
11,8,1,0,0,1,0,1,8.000000
12,21,-1,0,0,1,1,0,-27.584842
13,49,1,0,0,1,1,0,49.000000
14,20,-1,0,0,1,1,1,-25.004627
15,28,1,0,0,1,1,1,28.000000
16,120,-1,0,1,0,0,0,-145.589410
17,132,1,0,1,0,0,0,132.000000
18,41,-1,0,1,0,0,1,-47.881942
19,32,1,0,1,0,0,1,32.000000
20,264,-1,0,1,0,1,0,-396.088583
21,411,1,0,1,0,1,0,411.000000
22,144,-1,0,1,0,1,1,-198.563470
23,179,1,0,1,0,1,1,179.000000
24,20,-1,0,1,1,0,0,-21.097639
25,37,1,0,1,1,0,0,37.000000
26,2,-1,0,1,1,0,1,-1.937377
27,1,1,0,1,1,0,1,1.000000
28,45,-1,0,1,1,1,0,-57.332376
29,74,1,0,1,1,1,0,74.000000
30,12,-1,0,1,1,1,1,-14.605851
31,15,1,0,1,1,1,1,15.000000
32,22,-1,1,0,0,0,0,-27.885912
33,31,1,1,0,0,0,0,31.000000
34,7,-1,1,0,0,0,1,-8.659386
35,11,1,1,0,0,0,1,11.000000
36,75,-1,1,0,0,1,0,-107.559791
37,107,1,1,0,0,1,0,107.000000
38,35,-1,1,0,0,1,1,-42.827020
39,37,1,1,0,0,1,1,37.000000
40,18,-1,1,0,1,0,0,-20.160913
41,8,1,1,0,1,0,0,8.000000
42,3,1,1,0,1,0,1,3.000000
43,10,-1,1,0,1,1,0,-13.023880
44,31,1,1,0,1,1,0,31.000000
45,2,-1,1,0,1,1,1,-1.892533
46,2,1,1,0,1,1,1,2.000000
47,58,-1,1,1,0,0,0,-68.922620
48,103,1,1,1,0,0,0,103.000000
49,6,-1,1,1,0,0,1,-5.747279
50,7,1,1,1,0,0,1,7.000000
51,130,-1,1,1,0,1,0,-183.026997
52,200,1,1,1,0,1,0,200.000000
53,25,-1,1,1,0,1,1,-34.546069
54,21,1,1,1,0,1,1,21.000000
55,8,-1,1,1,1,0,0,-8.380838
56,17,1,1,1,1,0,0,17.000000
57,1,1,1,1,1,0,1,1.000000
58,20,-1,1,1,1,1,0,-23.016537
59,26,1,1,1,1,1,0,26.000000
60,5,-1,1,1,1,1,1,-6.285005
61,1,1,1,1,1,1,1,1.000000