In [19]:
import pandas as pd
import __init__

from db.pgdf import PgDf
from db.postgresql import PostgreSqlDB

d = PostgreSqlDB()
pg = PgDf()

df = None
for (codename,) in d.execSql("SELECT distinct codename from zz_strtg_params;"):
    df_s = pg.read_sql("SELECT * FROM zz_strtg_params WHERE codename = '%s' ORDER BY ep;" % (codename))
    df_t = pg.read_sql("""SELECT 
open_datetime as odt, codename as tcodename, 
CASE WHEN result = 'lose' THEN -1
    WHEN result = 'win' THEN 1
    ELSE 0
END AS res
FROM trades 
WHERE trade_name = 'anal_zigzag' 
AND codename = '%s'
ORDER BY open_epoch, codename;""" % (codename))
    df_tmp = df_t.join(df_s, how='left')
    if df is None:
          df = df_tmp
    else:
        df = pd.concat([df, df_tmp], ignore_index=True)

/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)
/tmp/ipykernel_3414686/529022672.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)

In [20]:
df = df[["res","vol_rank","prefer_recent_peaks","mado","trend_rate","long_candle","chiko","len_std","hara_rate","up_hige_rate","dw_hige_rate","len_avg"]]
df

,res,vol_rank,prefer_recent_peaks,mado,trend_rate,long_candle,chiko,len_std,hara_rate,up_hige_rate,dw_hige_rate,len_avg
0,-1,92,1,-0.015014,0.750000,0,1.0,-0.512360,-0.740741,0.259259,0.000000,26.316673
1,-1,90,1,0.012510,1.000000,0,1.0,0.000000,-0.678571,0.107143,0.214286,18.335617
2,1,89,0,-0.000869,1.000000,0,1.0,1.318761,-0.866667,0.033333,0.100000,17.370585
3,1,88,1,-0.002457,1.000000,0,1.0,-1.167149,0.384615,0.423077,0.192308,17.563591
4,1,8,0,0.000000,0.666667,0,0.4,1.868523,-0.974359,0.000000,0.025641,110.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
899,-1,25,1,0.009788,0.750000,0,0.6,-1.172794,-0.103774,0.122642,0.773585,51.400000
900,1,24,1,-0.028310,1.000000,0,0.6,1.104653,-0.735099,0.165563,0.099338,67.200000
901,1,17,1,-0.018634,0.750000,0,0.2,1.886153,-0.694268,0.146497,0.159236,40.630906
902,1,16,1,0.002660,1.000000,0,0.4,-0.635851,-0.289855,0.275362,0.434783,41.214125
903,1,14,1,0.014798,1.000000,0,1.0,-0.371960,-0.145038,0.221374,0.633588,28.269268

In [21]:
df.corr()

,res,vol_rank,prefer_recent_peaks,mado,trend_rate,long_candle,chiko,len_std,hara_rate,up_hige_rate,dw_hige_rate,len_avg
res,1.000000,-0.024596,0.029774,-0.014587,-0.030874,0.058651,0.030006,0.004787,0.007545,-0.029837,0.001632,0.004804
vol_rank,-0.024596,1.000000,-0.004776,0.053847,0.006587,-0.026165,-0.010196,-0.024636,-0.015554,0.005602,-0.001511,0.006244
prefer_recent_peaks,0.029774,-0.004776,1.000000,-0.139196,-0.114079,0.091626,-0.140386,-0.105906,0.268071,-0.017016,0.174342,0.021991
mado,-0.014587,0.053847,-0.139196,1.000000,-0.042386,-0.062236,-0.144070,-0.077677,-0.141624,-0.026707,0.081029,-0.123142
trend_rate,-0.030874,0.006587,-0.114079,-0.042386,1.000000,-0.098373,-0.082164,0.013252,-0.194970,0.018815,-0.025105,-0.018684
long_candle,0.058651,-0.026165,0.091626,-0.062236,-0.098373,1.000000,0.091951,0.195244,0.284401,-0.116916,-0.149045,0.003833
chiko,0.030006,-0.010196,-0.140386,-0.144070,-0.082164,0.091951,1.000000,0.016695,0.058278,0.085238,-0.082416,-0.063504
len_std,0.004787,-0.024636,-0.105906,-0.077677,0.013252,0.195244,0.016695,1.000000,-0.238736,-0.514535,-0.592435,-0.026717
hara_rate,0.007545,-0.015554,0.268071,-0.141624,-0.194970,0.284401,0.058278,-0.238736,1.000000,0.212956,0.212577,0.003126
up_hige_rate,-0.029837,0.005602,-0.017016,-0.026707,0.018815,-0.116916,0.085238,-0.514535,0.212956,1.000000,-0.000328,-0.031546
dw_hige_rate,0.001632,-0.001511,0.174342,0.081029,-0.025105,-0.149045,-0.082416,-0.592435,0.212577,-0.000328,1.000000,-0.012321
len_avg,0.004804,0.006244,0.021991,-0.123142,-0.018684,0.003833,-0.063504,-0.026717,0.003126,-0.031546,-0.012321,1.000000